### ISSUE TITLE
Не работают функции

### ISSUE THREAD

**Issue by selezneww** [4vanyek/seleznevv-blog#1]
Не работает вывод новостей
Не показывается задний фон. Вот как в коде сейчас
```css
.background {
    background-image: url('bg.jpg');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    filter: blur(5px);
    -webkit-filter: blur(5px);
}
``` 
```html
<div class="background"></div>
``` 
Тобишь, задний фон задается пустому блоку background,  и если в блоке ничего нет, то фона и не будет (но это не точно).
Предлагаю заменить на:
```css
body {
    background-image: url('bg.jpg');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    filter: blur(5px);
    -webkit-filter: blur(5px);
}
``` 
А блок в html удалить полностю.
